# Generated by Django 4.0.6 on 2022-12-27 05:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('description', models.CharField(default='Product Description', max_length=2000, verbose_name='Description')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('category', models.CharField(choices=[('Hats', 'Hats'), ('Shirts', 'Shirts'), ('Bottoms', 'Bottoms')], db_index=True, max_length=30, verbose_name='Category')),
                ('filter', models.CharField(choices=[("Men's", "Men's"), ("Women's", "Women's")], db_index=True, max_length=30, verbose_name='Filter')),
                ('in_stock', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=30, verbose_name='In Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
